name: development

on:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set-up-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: provision
        run: make provision

      - name: check
        run: make check

      - name: test
        run: make test

      - name: get version
        run: |
          ./bin/sbot update version
          echo "current version: $(./bin/sbot get version)"
