name: main

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: set-up-go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: provision
        run: make provision

      - name: check
        run: make check

      - name: build
        run: make build

      - name: test
        run: make test

      - name: release
        run: |
          ./bin/sbot update version

          echo "current version: $(./bin/sbot get version)"
          echo "next version: $(./bin/sbot predict version)"

          ./bin/sbot release version
          ./bin/sbot push version
